# Generated by Django 3.1.3 on 2020-12-04 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('province', models.CharField(choices=[('', 'Select province'), ('WC', 'Western Cape'), ('NC', 'Northern Cape'), ('EC', 'Eastern Cape'), ('FS', 'Free State'), ('N', 'KwaZulu-Natal'), ('G', 'Gauteng'), ('NW', 'North West'), ('MP', 'Mpumalanga'), ('LM', 'Limpopo')], max_length=100)),
                ('zip_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=40)),
                ('suburb', models.CharField(blank=True, max_length=40, null=True)),
                ('street_address', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('is_billing', models.BooleanField(default=True, verbose_name='Billing address')),
                ('is_shipping', models.BooleanField(default=True, verbose_name='Shipping address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
