# Generated by Django 3.1.3 on 2020-12-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201213_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='successful',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('P', 'PROCESSING'), ('C', 'CANCELLED'), ('S', 'SUCCESSFUL')], default='P', max_length=20),
        ),
    ]
