# Generated by Django 3.1.3 on 2020-12-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201214_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('P', 'PROCESSING'), ('C', 'CANCELLED'), ('S', 'SUCCESSFUL'), ('U', 'UNSUCCESSFUL')], default='P', max_length=20),
        ),
    ]
